version: '3.8'

services:
  mssql-chatdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-chatdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Adminsnater123!
    ports:
      - "1433:1433"
    volumes:
      - ~/apps/mssql/data:/var/lib/mssql/data
