apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: chat-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  selector:
    matchLabels:
      app: chat-service
  replicas: 3
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - name: chat-service
        image: joepbohlken/snater.snater.services.chat:release
        imagePullPolicy: Always
        ports:
        - containerPort: 80