apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: chat-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  selector:
    matchLabels:
      app: chat-service
  replicas: 3
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - name: chat-service
        image: joepbohlken/snater-snater.services.chats:development
        imagePullPolicy: Always
        resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
        ports:
        - containerPort: 80

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: chats-service-hpa
  namespace: default
spec:
  maxReplicas: 20
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chat-service
  targetCPUUtilizationPercentage: 70