kind: StorageClass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
  labels: 
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi