name: "microservice build & deploy - DockerHub"
on:
  workflow_call:
    inputs:
      project-location:
        required: true
        type: string
        description: "Path to project files"
      project-name:
        required: true
        type: string
        description: "Name of the project"
    secrets:
      docker-username:
        required: true
      docker-token:
        required: true

jobs:
  build-push-docker:
    runs-on: ubuntu-20.04
    steps:
      - name: "checkout project code"
        uses: actions/checkout@v2

      # Login to Dockerhub
      - name: "Login to DockerHub"
        run: docker login -u ${{ secrets.docker-username }} -p ${{ secrets.docker-token }}

      # Build docker image
      - name: "Build Docker image"
        run: docker build -t ${{ secrets.docker-username }}/snater-${{ inputs.project-name }}:$BRANCH_NAME ${{ inputs.project-location }}
        env:
          BRANCH_NAME: ${{ github.ref_name }}

      # Push docker image
      - name: "Push Docker image"
        run: docker push ${{ secrets.docker-username }}/snater-${{ inputs.project-name }}:$BRANCH_NAME
        env:
          BRANCH_NAME: ${{ github.ref_name }}