name: "Friends Service - build, test & analyse"
on:
  push:
    branches:
      - "main"
      - "development"
    paths:
      - "snater-backend/Snater.Services.Friends/**"
      - ".github/workflows/snater.service.friends.yml"
      - "snater-backend/Snater.Services.Friends.Test/**"
  pull_request:
    branches:
      - "main"
      - "development"
    paths:
      - "snater-backend/Snater.Services.Friends/**"
      - ".github/workflows/Snater.service.friends.yml"
      - "snater-backend/Snater.Services.Friends.Test/**"

jobs:
  chat-build-unit-testing:
    uses: "./.github/workflows/microservice-test-template.yml"
    with:
      project-location: "snater-backend/Snater.Services.Friends"
      test-location: "snater-backend/Snater.Services.Friends.Test"
  chat-analyse:
    uses: "./.github/workflows/microservice-analyse-template.yml"
    with:
      project-location: "snater-backend/Snater.Services.Friends"
      test-location: "snater-backend/Snater.Services.Friends.Test"
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}