name: "Chats Service - build, test & analyse"
on:
  push:
    branches:
      - "main"
      - "development"
    paths:
      - "snater-backend/Snater.Services.Chats/**"
      - ".github/workflows/snater.service.chats.yml"
      - "snater-backend/Snater.Services.Chats.Test/**"
  pull_request:
    branches:
      - "main"
      - "development"
    paths:
      - "snater-backend/Snater.Services.Chats/**"
      - ".github/workflows/Snater.service.chats.yml"
      - "snater-backend/Snater.Services.Chats.Test/**"

jobs:
  # Tests
  chat-build-unit-testing:
    uses: "./.github/workflows/microservice-test-template.yml"
    with:
      project-location: "snater-backend/Snater.Services.Chats"
      test-location: "snater-backend/Snater.Services.Chats.Test"

  # Sonarcloud analyses
  chat-analyse:
    uses: "./.github/workflows/microservice-analyse-template.yml"
    with:
      project-location: "snater-backend/Snater.Services.Chats"
      test-location: "snater-backend/Snater.Services.Chats.Test"
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}

  # Docker build-push
  chat-build-push:
    uses: "./.github/workflows/microservice-docker-build-push-template.yml"
    if: github.ref_name == 'release'
    with:
      project-name: "snater.services.chat"
      project-location: "snater-backend/Snater.Services.Chats"
    secrets:
      docker-token: ${{ secrets.DOCKER_TOKEN}}
      docker-username: ${{ secrets.DOCKER_USERNAME}}
